services:
  - type: worker
    name: discord-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 python_bot/src/main.py
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: LOG_LEVEL
        value: info
      - key: TOKEN
        sync: false
      - key: MONGODB_URI
        sync: false
