server: # REST and WS server
  port: 2333
  address: 0.0.0.0 # Change to 0.0.0.0 to accept connections from anywhere
lavalink:
  server:
    password: "youshallnotpass"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: true # Enable local files
    bufferDurationMs: 600 # Increased buffer for better playback
    youtubePlaylistLoadLimit: 10 # Increased to handle larger playlists
    playerUpdateInterval: 3 # More frequent updates
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true
    # Retry settings for YouTube and SoundCloud
    youtube:
      maximumLoadRetries: 5
      retryDelay: 3000
    soundcloud:
      maximumLoadRetries: 3
      retryDelay: 1500
    # HTTP settings
    httpConfig:
      followRedirects: true
      connectTimeout: 10000
      readTimeout: 10000
      userAgent: "LavaLink/1.0"

metrics:
  prometheus:
    enabled: true
    endpoint: /metrics

sentry:
  dsn: ""
  environment: ""

logging:
  file:
    max-history: 30
    max-size: 1GB
  path: ./logs/

  level:
    root: INFO
    lavalink: INFO
    # More detailed logging for specific components
    com.sedmelluq.discord.lavaplayer: INFO
    com.sedmelluq.lava.common: INFO
